### ISSUE TITLE
Problem in dispensing on Polygon because MOCEAN not OCEAN

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#177]
**Background**

Berkay in slack:

we had a problem when dispensing and calculating rewards for polygon, because the symbols didn't match MOCEAN - OCEAN

I changed the MOCEAN to OCEAN in the approved tokens csv file - calc worked (edited) 

for dispensing I added the following line as a temproray fix:
token_symbol = token_symbol.upper().replace("MOCEAN", "OCEAN")

**TODOs for this issue**

The above showed the workaround for DF1.

The aim of this issue is to implement a non-hacky solution for future rounds.

**Comment by trentmc** [comment]
Here's the diff.
```text
(venv) trentmc@trentmc-xps:~/code/df-py$ git diff
diff --git a/dftool b/dftool
index adcb1f9..c7c7683 100755
--- a/dftool
+++ b/dftool
@@ -276,7 +276,7 @@ Transactions are signed with envvar 'DFTOOL_KEY`.
     # main work
     networkutil.connect(CHAINID)
     from_account = _getPrivateAccount()
-    token_symbol = B.Simpletoken.at(TOKEN_ADDR).symbol()
+    token_symbol = B.Simpletoken.at(TOKEN_ADDR).symbol().upper().replace("MOCEAN", "OCEAN")
     rewards = csvs.loadRewardsCsv(CSV_DIR, token_symbol)
     dispense.dispense(
         rewards[CHAINID],
diff --git a/util/query.py b/util/query.py
index 91a07bd..23eb4e7 100644
--- a/util/query.py
+++ b/util/query.py
@@ -328,6 +328,7 @@ def getApprovedTokens(chainID: int) -> TokSet:
     for x in result["data"]["opcs"][0]["approvedTokens"]:
         addr = x["id"].lower()
         symb = B.Simpletoken.at(addr).symbol().upper()
+        symb.replace("MOCEAN", "OCEAN") # for Polygon
         approved_tokens.add(chainID, addr, symb)
 
     return approved_tokens
```

**Comment by trentmc** [comment]
Note: the commit just above is because I had seen the following error during dftool dispense. The commit fixed the error.

```text
(venv) trentmc@trentmc-xps:~/code/df-py$ dftool dispense mydata 137 $dfrewards_addr $OCEAN_137_addr #polygon
Arguments: CSV_DIR=mydata, CHAINID=137, DFREWARDS_ADDR=0x0cea7DA063EA910D6904299b5A29A8b68DBC1947, TOKEN_ADDR=0x282d8efce846a88b159800bd4130ad77443fa1a1, BATCH_NBR=None
For private key DFTOOL_KEY, address is: 0x17f337f49dC66303925a47514B1cdC94DdBCC12b
Traceback (most recent call last):
  File "/home/trentmc/code/df-py/./dftool", line 757, in <module>
    do_main()
  File "/home/trentmc/code/df-py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/df-py/./dftool", line 724, in do_main
    do_dispense()
  File "/home/trentmc/code/df-py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/df-py/./dftool", line 298, in do_dispense
    rewards = csvs.loadRewardsCsv(CSV_DIR, token_symbol)
  File "/home/trentmc/code/df-py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/df-py/util/csvs.py", line 665, in loadRewardsCsv
    with open(csv_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mydata/rewardsperlp-MOCEAN.csv'
```
