### ISSUE TITLE
df-py remote test_query and test_dftool failing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#180]
These are the two tests that do queries against ganache. Somehow it's having trouble

Example failed run:
https://github.com/oceanprotocol/df-py/runs/7071352525?check_suite_focus=true#step:8:1037

Failing test commands:
```text
=========================== short test summary info ============================
FAILED util/test/test_dftool.py::test_query - AssertionError: assert []
FAILED util/test/test_end-to-end.py::test_without_csvs - KeyError: 'lastPrice...
FAILED util/test/test_end-to-end.py::test_with_csvs - KeyError: 'lastPriceToken'
FAILED util/test/test_query.py::test_all - KeyError: 'lastPriceToken'
============ 4 failed, 109 passed, 26 warnings in 395.64s (0:06:35) ============
```

Full log:
```text
=================================== FAILURES ===================================
__________________________________ test_query __________________________________
tmp_path = PosixPath('/tmp/pytest-of-runner/pytest-0/test_query0')
    @enforce_types
    def test_query(tmp_path):
        # insert fake inputs: info onto the chain
        oceantestutil.fillAccountsWithOCEAN()
        num_pools = 1
        OCEAN = oceanutil.OCEANtoken()
        oceantestutil.randomDeployTokensAndPoolsThenConsume(num_pools, OCEAN)
        time.sleep(2)
        # main cmd
        ST = 0
        FIN = "latest"
        NSAMP = 5
        CSV_DIR = str(tmp_path)
        cmd = f"./dftool query {ST} {FIN} {NSAMP} {CSV_DIR} {CHAINID}"
        os.system(cmd)
        # test result
>       assert csvs.stakesCsvFilenames(CSV_DIR)
E       AssertionError: assert []
E        +  where [] = <function stakesCsvFilenames at 0x7f97b93403a0>('/tmp/pytest-of-runner/pytest-0/test_query0')
E        +    where <function stakesCsvFilenames at 0x7f97b93403a0> = csvs.stakesCsvFilenames
util/test/test_dftool.py:39: AssertionError
---------------------------- Captured stdout setup -----------------------------
mnemonic: 'system early fold trim grit around broken access need distance logic attack'
----------------------------- Captured stdout call -----------------------------
fillAccountsWithToken(Ocean), balances after:
  Account #0 has 91000.0 Ocean
  Account #1 has 1000.0 Ocean
  Account #2 has 1000.0 Ocean
  Account #3 has 1000.0 Ocean
  Account #4 has 1000.0 Ocean
  Account #5 has 1000.0 Ocean
  Account #6 has 1000.0 Ocean
  Account #7 has 1000.0 Ocean
  Account #8 has 1000.0 Ocean
  Account #9 has 1000.0 Ocean
Compiling contracts...
  Solc version: 0.8.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
Generating build data...
 - OpenZeppelin/openzeppelin-contracts@4.2.0/ReentrancyGuard
 - OpenZeppelin/openzeppelin-contracts@4.2.0/IERC20
 - OpenZeppelin/openzeppelin-contracts@4.2.0/SafeERC20
 - OpenZeppelin/openzeppelin-contracts@4.2.0/Address
 - OpenZeppelin/openzeppelin-contracts@4.2.0/SafeMath
 - DFStrategyV1
 - IDFRewards
 - IPool
 - IDispenser
 - IERC20
 - IERC20Template
 - IERC721Template
 - IFactory
 - IFactoryRouter
 - IFixedRateExchange
 - IPool
 - ISideStaking
 - FactoryRouter
 - BConst
 - BFactory
 - BMath
 - BNum
 - BPool
 - BToken
 - BTokenBase
 - SideStaking
 - Deployer
 - Address
 - SafeERC20
dftool query: Begin
Arguments:
 ST=0
 FIN=latest
 NSAMP=5
 CSV_DIR=/tmp/pytest-of-runner/pytest-0/test_query0
 CHAINID=8996
Envvar:
 ADDRESS_FILE=/home/runner/.ocean/ocean-contracts/artifacts/address.json
Attached to local RPC client listening at '127.0.0.1:8545'...
getStakes(): begin
  20.0% done
  100.0% done
getDTVolumes(): begin
----------------------------- Captured stderr call -----------------------------
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/main.py:44: BrownieEnvironmentWarning: Development network has a block height of 164
  warnings.warn(
Traceback (most recent call last):
  File "./dftool", line 726, in <module>
    do_main()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "./dftool", line 687, in do_main
    do_query()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "./dftool", line 136, in do_query
    (Pi, Si, Vi, Ai) = query.query_all(rng, CHAINID)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/df-py/df-py/util/query.py", line 70, in query_all
    Vi = getPoolVolumes(Pi, rng.st, rng.fin, chainID)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/df-py/df-py/util/query.py", line 196, in getPoolVolumes
    DTvols_at_chain = getDTVolumes(st_block, end_block, chainID)
  File "/home/runner/work/df-py/df-py/util/query.py", line 259, in getDTVolumes
    basetoken_addr = order["lastPriceToken"]
KeyError: 'lastPriceToken'
______________________________ test_without_csvs _______________________________
    @enforce_types
    def test_without_csvs():
        chainID = networkutil.DEV_CHAINID
        st, fin, n = 1, len(brownie.network.chain), 25
        rng = blockrange.BlockRange(st, fin, n)
>       (_, S0, V0, A0) = query.query_all(rng, chainID)
util/test/test_end-to-end.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/query.py:70: in query_all
    Vi = getPoolVolumes(Pi, rng.st, rng.fin, chainID)
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/query.py:196: in getPoolVolumes
    DTvols_at_chain = getDTVolumes(st_block, end_block, chainID)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
st_block = 1, end_block = 300, chainID = 8996
    def getDTVolumes(
        st_block: int, end_block: int, chainID: int
    ) -> Dict[str, Dict[str, float]]:
        """
        @description
          Query the chain for datatoken (DT) volumes within the given block range.
        @return
          DTvols_at_chain -- dict of [basetoken_addr][DT_addr]:vol_amt
        """
        print("getDTVolumes(): begin")
        DTvols: Dict[str, Dict[str, float]] = {}
        chunk_size = 1000  # max for subgraph = 1000
        offset = 0
        while True:
            query = """
            {
              orders(where: {block_gte:%s, block_lte:%s}, skip:%s, first:%s) {
                id,
                datatoken {
                  id
                },
                lastPriceToken,
                lastPriceValue,
                block
              }
            }
            """ % (
                st_block,
                end_block,
                offset,
                chunk_size,
            )
            offset += chunk_size
            result = submitQuery(query, chainID)
            new_orders = result["data"]["orders"]
            if new_orders == []:
                break
            for order in new_orders:
                lastPriceValue = float(order["lastPriceValue"])
                if lastPriceValue == 0:
                    continue
                DT_addr = order["datatoken"]["id"].lower()
>               basetoken_addr = order["lastPriceToken"]
E               KeyError: 'lastPriceToken'
util/query.py:259: KeyError
---------------------------- Captured stdout setup -----------------------------
fillAccountsWithToken(Ocean), balances after:
  Account #0 has 80711.64160342768 Ocean
  Account #1 has 1866.3725886889977 Ocean
  Account #2 has 1883.8970450610054 Ocean
  Account #3 has 1884.8209369073527 Ocean
  Account #4 has 1886.8816667243427 Ocean
  Account #5 has 1883.3242936401102 Ocean
  Account #6 has 1861.4868577571556 Ocean
  Account #7 has 1858.2978030695474 Ocean
  Account #8 has 1862.5874963101687 Ocean
  Account #9 has 1847.187212540704 Ocean
----------------------------- Captured stdout call -----------------------------
getStakes(): begin
  4.0% done
  100.0% done
getDTVolumes(): begin
________________________________ test_with_csvs ________________________________
tmp_path = PosixPath('/tmp/pytest-of-runner/pytest-0/test_with_csvs0')
    @enforce_types
    def test_with_csvs(tmp_path):
        """
        Simulate these steps, with csvs in between
        1. dftool query
        2. dftool getrate
        3. dftool calc
        4. dftool dispense
        """
        chainID = networkutil.DEV_CHAINID
        csv_dir = str(tmp_path)
        st, fin, n = 1, len(brownie.network.chain), 25
        rng = blockrange.BlockRange(st, fin, n)
        token_addr = oceanutil.OCEAN_address()
        # 1. simulate "dftool query"
>       (_, S0, V0, A0) = query.query_all(rng, chainID)
util/test/test_end-to-end.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/query.py:70: in query_all
    Vi = getPoolVolumes(Pi, rng.st, rng.fin, chainID)
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/query.py:196: in getPoolVolumes
    DTvols_at_chain = getDTVolumes(st_block, end_block, chainID)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
st_block = 1, end_block = 317, chainID = 8996
    def getDTVolumes(
        st_block: int, end_block: int, chainID: int
    ) -> Dict[str, Dict[str, float]]:
        """
        @description
          Query the chain for datatoken (DT) volumes within the given block range.
        @return
          DTvols_at_chain -- dict of [basetoken_addr][DT_addr]:vol_amt
        """
        print("getDTVolumes(): begin")
        DTvols: Dict[str, Dict[str, float]] = {}
        chunk_size = 1000  # max for subgraph = 1000
        offset = 0
        while True:
            query = """
            {
              orders(where: {block_gte:%s, block_lte:%s}, skip:%s, first:%s) {
                id,
                datatoken {
                  id
                },
                lastPriceToken,
                lastPriceValue,
                block
              }
            }
            """ % (
                st_block,
                end_block,
                offset,
                chunk_size,
            )
            offset += chunk_size
            result = submitQuery(query, chainID)
            new_orders = result["data"]["orders"]
            if new_orders == []:
                break
            for order in new_orders:
                lastPriceValue = float(order["lastPriceValue"])
                if lastPriceValue == 0:
                    continue
                DT_addr = order["datatoken"]["id"].lower()
>               basetoken_addr = order["lastPriceToken"]
E               KeyError: 'lastPriceToken'
util/query.py:259: KeyError
---------------------------- Captured stdout setup -----------------------------
fillAccountsWithToken(Ocean), balances after:
  Account #0 has 80608.03331885362 Ocean
  Account #1 has 1866.3725886889977 Ocean
  Account #2 has 1883.8970450610054 Ocean
  Account #3 has 1884.8209369073527 Ocean
  Account #4 has 1885.9079332444296 Ocean
  Account #5 has 1883.3242936401102 Ocean
  Account #6 has 1859.5390603895637 Ocean
  Account #7 has 1847.7286759848182 Ocean
  Account #8 has 1862.5874963101687 Ocean
  Account #9 has 1836.995126269579 Ocean
----------------------------- Captured stdout call -----------------------------
getStakes(): begin
  4.0% done
  100.0% done
getDTVolumes(): begin
___________________________________ test_all ___________________________________
    @pytest.mark.timeout(300)
    def test_all():
        """Run this all as a single test, because we may have to
        re-loop or sleep until the info we want is there."""
        OCEAN = oceanutil.OCEANtoken()
        oceantestutil.fillAccountsWithToken(OCEAN)
        CO2_SYM = f"CO2_{random.randint(0,99999):05d}"
        CO2 = B.Simpletoken.deploy(CO2_SYM, CO2_SYM, 18, 1e26, {"from": account0})
        CO2_ADDR = CO2.address.lower()
        oceantestutil.fillAccountsWithToken(CO2)
        # keep deploying, until TheGraph node sees volume, or timeout
        # (assumes that with volume, everything else is there too
        for loop_i in range(100):
            print(f"loop {loop_i} start")
            assert loop_i < 5, "timeout"
>           if _foundStakeAndConsume(CO2_ADDR):
util/test/test_query.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
util/test/test_query.py:70: in _foundStakeAndConsume
    DT_vols = query.getDTVolumes(st, fin, CHAINID)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
st_block = 124, end_block = 384, chainID = 8996
    def getDTVolumes(
        st_block: int, end_block: int, chainID: int
    ) -> Dict[str, Dict[str, float]]:
        """
        @description
          Query the chain for datatoken (DT) volumes within the given block range.
        @return
          DTvols_at_chain -- dict of [basetoken_addr][DT_addr]:vol_amt
        """
        print("getDTVolumes(): begin")
        DTvols: Dict[str, Dict[str, float]] = {}
        chunk_size = 1000  # max for subgraph = 1000
        offset = 0
        while True:
            query = """
            {
              orders(where: {block_gte:%s, block_lte:%s}, skip:%s, first:%s) {
                id,
                datatoken {
                  id
                },
                lastPriceToken,
                lastPriceValue,
                block
              }
            }
            """ % (
                st_block,
                end_block,
                offset,
                chunk_size,
            )
            offset += chunk_size
            result = submitQuery(query, chainID)
            new_orders = result["data"]["orders"]
            if new_orders == []:
                break
            for order in new_orders:
                lastPriceValue = float(order["lastPriceValue"])
                if lastPriceValue == 0:
                    continue
                DT_addr = order["datatoken"]["id"].lower()
>               basetoken_addr = order["lastPriceToken"]
E               KeyError: 'lastPriceToken'
util/query.py:259: KeyError
----------------------------- Captured stdout call -----------------------------
fillAccountsWithToken(Ocean), balances after:
  Account #0 has 78501.01273936545 Ocean
  Account #1 has 1856.1637703382648 Ocean
  Account #2 has 1883.8970450610054 Ocean
  Account #3 has 1883.7862830069669 Ocean
  Account #4 has 1885.9079332444296 Ocean
  Account #5 has 1883.3242936401102 Ocean
  Account #6 has 1859.5390603895637 Ocean
  Account #7 has 1847.7286759848182 Ocean
  Account #8 has 1849.4768309659642 Ocean
  Account #9 has 1836.995126269579 Ocean
fillAccountsWithToken(CO2_19725), balances after:
  Account #0 has 99991000.00000001 CO2_19725
  Account #1 has 1000.0 CO2_19725
  Account #2 has 1000.0 CO2_19725
  Account #3 has 1000.0 CO2_19725
  Account #4 has 1000.0 CO2_19725
  Account #5 has 1000.0 CO2_19725
  Account #6 has 1000.0 CO2_19725
  Account #7 has 1000.0 CO2_19725
  Account #8 has 1000.0 CO2_19725
  Account #9 has 1000.0 CO2_19725
loop 0 start
getStakes(): begin
  5.0% done
  100.0% done
loop 0 not successful, so sleep and re-loop
loop 1 start
getStakes(): begin
  5.0% done
  100.0% done
getDTVolumes(): begin
=============================== warnings summary ===============================
util/test/test_query.py:18
  /home/runner/work/df-py/df-py/util/test/test_query.py:18: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.timeout(300)
../../../../../opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/main.py:44
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/main.py:44: BrownieEnvironmentWarning: Development network has a block height of 18
    warnings.warn(
util/test/test_DFRewards_withdraw.py::test_erc20_withdraw_main
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-212
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/rpc/ganache.py", line 125, in _request
      response = web3.provider.make_request(method, args)  # type: ignore
  AttributeError: 'NoneType' object has no attribute 'make_request'
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/state.py", line 332, in _add_to_undo_buffer
      self.sleep(0)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/state.py", line 375, in sleep
      self._time_offset = int(rpc.Rpc().sleep(seconds))
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/rpc/__init__.py", line 46, in wrapped
      return fn(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/rpc/__init__.py", line 167, in sleep
      return self.backend.sleep(seconds)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/rpc/ganache.py", line 134, in sleep
      return _request("evm_increaseTime", [seconds])
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/rpc/ganache.py", line 129, in _request
      raise RPCRequestError("Web3 is not connected.")
  brownie.exceptions.RPCRequestError: Web3 is not connected.
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
util/test/test_dftool.py::test_query
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xb38b5A1A0B7c48099a8C53dD179726bf8A416538: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_dftool.py::test_query
util/test/test_end-to-end.py::test_without_csvs
util/test/test_end-to-end.py::test_with_csvs
util/test/test_oceanutil.py::test_createBPoolFromDatatoken
util/test/test_query.py::test_all
util/test/test_query.py::test_stakes_shares_conversion
util/test/test_thegraph.py::test_approvedTokens
util/test/test_thegraph.py::test_orders
util/test/test_thegraph.py::test_poolShares
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x2473f4F7bf40ed9310838edFCA6262C17A59DF64: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_end-to-end.py::test_without_csvs
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x154C95fD69F46385d7BE443A8ca759DB805ee955: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_end-to-end.py::test_with_csvs
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x0E08dc9E8C45c2575A1Be2c0308B[500](https://github.com/oceanprotocol/df-py/runs/7071352525?check_suite_focus=true#step:8:501)2f2Ce5aEb: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_oceanutil.py::test_createDataNFT
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x623378c1c227b9816eF25987E320A4f4dC91401a: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_oceanutil.py::test_createDatatokenFromDataNFT
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xC4aA9eFe0EbeB672afA21cFFe583fDA35e405587: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_oceanutil.py::test_createBPoolFromDatatoken
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xeC8Ca9bc62268137A956A446f349b077f242941e: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_query.py::test_all
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xb862Ef9776D9afF1452A2C253458b5463Da63b7a: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_query.py::test_all
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x62f7ba8b1Fe7dF165c7ab3E905C097c62629adf5: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_query.py::test_all
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x592681bF9d562C79ac5E93C84E06Bfb4645Eec40: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_query.py::test_all
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x25e9903a748813EB7164178496896eC69[516](https://github.com/oceanprotocol/df-py/runs/7071352525?check_suite_focus=true#step:8:517)8f70: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_query.py::test_stakes_shares_conversion
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0x0E4e0AA1747Eac8c66a5A87E8DcA1f9f1FA775FD: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_thegraph.py::test_approvedTokens
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xc791dB2B8e700CF0CE4002CAD02cDa[520](https://github.com/oceanprotocol/df-py/runs/7071352525?check_suite_focus=true#step:8:521)C362ef3: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_thegraph.py::test_orders
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xB93ABfe4E0685915C29Aa212f2422Ea0052d3E92: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
util/test/test_thegraph.py::test_poolShares
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/brownie/network/event.py:490: UserWarning: 0xa072B0D477fae1aBE3537Ff66A8389B184E18F4d: Event log does not contain enough topics for the given ABI - this is usually because an event argument is not marked as indexed
    warnings.warn(f"{address}: {exc}")
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED util/test/test_dftool.py::test_query - AssertionError: assert []
FAILED util/test/test_end-to-end.py::test_without_csvs - KeyError: 'lastPrice...
FAILED util/test/test_end-to-end.py::test_with_csvs - KeyError: 'lastPriceToken'
FAILED util/test/test_query.py::test_all - KeyError: 'lastPriceToken'
============ 4 failed, 109 passed, 26 warnings in 395.64s (0:06:35) ============
Error: Process completed with exit code 1.
```

**Comment by trentmc** [comment]
Fewer tests failling now. But there's still a test failing remotely in querying.

https://github.com/oceanprotocol/df-py/runs/7130714130?check_suite_focus=true#step:8:586
