### ISSUE TITLE
Reconfigure flow.yml and other bootstrappres to use infura rpc + WEB3_INFURA_PROJECT_ID

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#434]
### Problem
We can't rely on public RPCs.
Active Rewards continued to fail until we found a public RPC that was table.

The flow.yml brownie bootstrapper fails in these situations
```
brownie networks add moonbase moonbase host=https://rpc.api.moonbase.moonbeam.network chainid=1287
brownie networks add mumbai mumbai host=https://matic-mumbai.chainstacklabs.com chainid=80001
brownie networks add energyweb energyweb host=https://rpc.energyweb.org chainid=246
brownie networks add polygon polygon host=https://matic-mainnet.chainstacklabs.com chainid=137
brownie networks add bsc bsc host=https://bsc-dataseed1.binance.org chainid=56
brownie networks add moonriver moonriver host=https://rpc.api.moonriver.moonbeam.network chainid=1285
```

### Solution
1. Modify our yml files, bootstrappers, and documentation, to use infura.
2. Make sure that the `brownie network add` command pipes the cout to null ` >> /dev/null`
3. Make sure that the brownie/request logic, is able to talk to the infura RPC provider. Right now, updating this configuration causes an HTTP request error to be thrown. I'll share this below. 

### Review:
Step 1 - Update bootstrapper to use infura RPCs for each network (wherever available) and to dereference the WEB3_INFURA_PROJECT_ID env_var. 
```
...
brownie networks add polygon polygon host=https://polygon-mainnet.infura.io/v3/${WEB3_INFURA_PROJECT_ID} chainid=137
...
```

Step 2 - Fix the brownie HTTP request to work w/ infura. If we just modify the above, the following error is triggered. So, please update whatever needs to happen internally for infura to work w/ brownie.
```
Traceback (most recent call last):
  File "./dftool", line 1053, in <module>
    do_main()
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "./dftool", line 1001, in do_main
    do_volsym()
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "./dftool", line 144, in do_volsym
    networkutil.connect(CHAINID)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/anon/df-py/util/networkutil.py", line 110, in connect
    network.connect(chainIdToNetwork(chainID))
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/brownie/network/main.py", line 55, in connect
    p._load_deployments()
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/brownie/project/main.py", line 372, in _load_deployments
    contract = Contract.from_abi(  # type: ignore
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 969, in from_abi
    _DeployedContractBase.__init__(self, address, owner, None)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 706, in __init__
    self.bytecode = web3.eth.get_code(address).hex()[
    2:
]
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/web3/_utils/request.py", line 103, in make_post_request
    response.raise_for_status()
  File "/home/anon/df-py/venv/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https: //polygon-mainnet.infura.io/v3/00000000000000000000000
```

### DoD:
- [ ] flow.yml and other GH Action workflows have been updated to use infura
- [ ] `brownie network add` commands redirect output to null, avoiding exposing INFURA_KEY
- [ ] HTTP request to via brownie works
- [ ] All documentation, bootstrapers, and any other places where this applies, have been updated to reflect this

**Comment by calina-c** [comment]
Not sure if related, but I've added a `sed` command to add WEB3_INFURA_PROJECT_ID in test.yml here: https://github.com/oceanprotocol/df-py/pull/559/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88

I am unclear whether that (or something similar) is the requirement of this issue. Disregard if so.
Please note that there are two sed commands added, the second one is unrelated and fixes a KeyError with brownie contract duplicates until that will be fixed in brownie itself :)

**Comment by trentmc** [comment]
@idiom-bytes could you comment here whether this github issue is still relevant, and if the spec is still accurate? (It was created 4+ mos ago)

**Comment by calina-c** [comment]
Here is a list of questions to help out clarify this issue:
- are all the networks added using `brownie networks add` (from flow.yml) necessary? It seems not all are supported by Infura. Should we keep a mixture of Infura and non-Infura networks?
- instead of using `brownie networks add`, could we modify the .network-config from brownie itself, as we do in ocean.py and currently in `test.yml`?
- the 403 error seems to be related to the infura key itself, where it is configured as 000000... instead of an actual key. Can this be confirmed?
- for documentation, we show some samples of adding the networks, I can add examples for adding Infura networks based on a project id, but it shouldn't affect much else. Anyone configuring their networks should be able to use any type of network.

It is also a bit unclear to me where the Dockerfile applies. If everything is ran through Github Actions, what is up with the Dockerfile?

**Comment by trentmc** [comment]
@idiom-bytes or @trizin can you answer @calina-c 's questions please?

**Comment by calina-c** [comment]
thank you @trizin. To follow-up:

regarding the key, I was just refering to the command @idiom-bytes tried. The command should run just fine with an actual key and I will test that.

so do you think a mixture of infura and others is fine?

also, I believe this issue too should wait for the Ci improvements. Do you agree?

**Comment by calina-c** [comment]
I think #586 handles everything, here is a screenshot of the CI showing that the Infura keys are not leaked (because they are secrets)
<img width="436" alt="Screenshot 2023-05-29 at 14 19 17" src="https://github.com/oceanprotocol/df-py/assets/4101015/ab042176-9670-42f0-85c5-e0b3eaa7c04d">

**Comment by trentmc** [comment]
@idiom-byteI can we close this issue then? See comments above
