### ISSUE TITLE
CI sporadic fail: test_timestrToBlock_eth_1(); can't see the chain

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#546]
### Background

I did a commit that only had trivial changes (removed some whitespace). Yet it failed.

This is a sporadic failure. I've been doing other commits today, and CI passes.

Traceback summary: (details below)

```text
util/blocktime.py:146: in ethTimestamptoBlock
    current_block = chain[-1].number
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/eth.py:690: in get_block
    return self._get_block(block_identifier, full_transactions)
 ...
    
>       raise BlockNotFound(message)
E       web3.exceptions.BlockNotFound: Block with id: '0x106a493' not found.
```

Another clue: there were many warnings. They hinted that it can't actually find the chain (ganache) at all.
```text
=============================== warnings summary ===============================
util/test/test_query.py:38
  /home/runner/work/df-py/df-py/util/test/test_query.py:38: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  
...

util/test/test_DFRewards_allocate_gas.py::test_1250_addresses
  /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-179
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/brownie/network/rpc/ganache.py", line 125, in _request
      response = web3.provider.make_request(method, args)  # type: ignore
  AttributeError: 'NoneType' object has no attribute 'make_request'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
...
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/brownie/network/rpc/ganache.py", line 134, in sleep
      return _request("evm_increaseTime", [seconds])
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/brownie/network/rpc/ganache.py", line 129, in _request
      raise RPCRequestError("Web3 is not connected.")
  brownie.exceptions.RPCRequestError: Web3 is not connected.
```

And
```text
====== 1 failed, 256 passed, 4 skipped, 248 warnings in 369.52s (0:06:09) ======
```

### Full log

[Here](https://github.com/oceanprotocol/df-py/actions/runs/4910400671/jobs/8767533197).

### Traceback

```text
=================================== FAILURES ===================================
__________________________ test_timestrToBlock_eth_1 ___________________________

    def test_timestrToBlock_eth_1():
        ts = chain[-5000].timestamp
        block = chain[-5000].number
    
        # convert ts to YYYY-MM-DD_HH:MM
        dt = datetime.fromtimestamp(ts)
        dt_str = dt.strftime("%Y-%m-%d_%H:%M:%S")
    
>       guess = timestrToBlock(chain, dt_str, True)

util/test/test_blocktime_eth_mainnet.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/blocktime.py:45: in timestrToBlock
    block = ethTimestamptoBlock(chain, timestamp)
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
util/blocktime.py:146: in ethTimestamptoBlock
    current_block = chain[-1].number
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/eth.py:690: in get_block
    return self._get_block(block_identifier, full_transactions)
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/module.py:57: in caller
    result = w3.manager.request_blocking(method_str,
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/manager.py:198: in request_blocking
    return self.formatted_response(response,
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/manager.py:177: in formatted_response
    apply_null_result_formatters(null_result_formatters, response, params)
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/manager.py:82: in apply_null_result_formatters
    formatted_resp = pipe(params, null_result_formatters)
cytoolz/functoolz.pyx:666: in cytoolz.functoolz.pipe
    ???
cytoolz/functoolz.pyx:641: in cytoolz.functoolz.c_pipe
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

params = ('0x106a493', False)

    def raise_block_not_found(params: Tuple[BlockIdentifier, bool]) -> NoReturn:
        try:
            block_identifier = params[0]
            message = f"Block with id: {block_identifier!r} not found."
        except IndexError:
            message = "Unknown block identifier"
    
>       raise BlockNotFound(message)
E       web3.exceptions.BlockNotFound: Block with id: '0x106a493' not found.

/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/web3/_utils/method_formatters.py:630: BlockNotFound
```

**Comment by trentmc** [comment]
In commit https://github.com/oceanprotocol/df-py/commit/11b6c2f320d34cdffe1368a3e77e8c0196cdb57d, Alex rearranged how df-py waits for barge on startup. Because of that, whatever errors there were previously wrt waiting for barge are now obsolete. That includes _this_ issue. Closing.

We can reopen a new issue if other problems emerge.
