### ISSUE TITLE
retryFunction() gives little debugging info, it can easily do better

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#565]
### Background motivation

Here's an example log that uses `retryFunction()`: (from [here](https://github.com/oceanprotocol/df-py/actions/runs/4942519287/jobs/8836117940)).
```text
  File "./dftool", line 172, in do_volsym
    (Vi, Ci, SYMi) = retryFunction(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/df-py/df-py/util/retry.py", line 29, in retryFunction
    raise Exception(f"failed after {retries} retries")
Exception: failed after 5 retries
Error: Process completed with exit code 1.
```

The problem: it only says "failed after x retries". But it could easily do better, by grabbing the _actual_ exception str and printing that out along with "failed after x retries".

### TODO

Grabbi the _actual_ exception str and print that out along with "failed after x retries".

**Comment by trentmc** [comment]
Nevermind, it already has this! :)

Eg for above, higher up in the traceback, there is:
```text
_queryVolsOwners(): begin
retry 0: {'errors': [{'message': 'Store error: database unavailable'}]}
_queryVolsOwners(): begin
retry 1: {'errors': [{'message': 'Store error: database unavailable'}]}
_queryVolsOwners(): begin
retry 2: {'errors': [{'message': 'Store error: database unavailable'}]}
_queryVolsOwners(): begin
retry 3: {'errors': [{'message': 'Store error: database unavailable'}]}
_queryVolsOwners(): begin
retry 4: {'errors': [{'message': 'Store error: database unavailable'}]}
Traceback (most recent call last):
```
